### ISSUE TITLE
Plunker doesn't work

### ISSUE THREAD

**Issue by brian15co** [jsvalley/ng2-tooltop#2]
https://plnkr.co/edit/keOHIe?p=preview  does not work

nor does https://plnkr.co/edit/keOHIe

Here is part of the traceback: `Error loading https://run.plnkr.co/y0gWRDxGimcFT5gU/ng2-map as "ng2-map" from https://npmcdn.com/ng2-ui/dist/index.js"`

Tried on firefox 47 and chrome 50

**Comment by allenhwkim** [comment]
Thanks for reporing this.

Here is working plunker. https://plnkr.co/edit/6reiaH?p=preview

The existing plunker is outdated, and needs to be updated.

**Comment by allenhwkim** [comment]
Plunker is updated at README.md with  https://plnkr.co/edit/6reiaH?p=preview
